// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:03de9159-5910-41e3-8c47-b776f86a4e5e',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'note-hosting-mobilehub-1296620368',
    'aws_content_delivery_bucket_region': 'sa-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd132lbr9ncwm6l.cloudfront.net',
    'aws_mobile_analytics_app_id': 'a875ae13085b483292d766d35b8b244f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'aee1e9b7-16b6-11e8-b5df-89121fa705ee',
    'aws_project_name': 'note2',
    'aws_project_region': 'sa-east-1',
    'aws_resource_name_prefix': 'note-mobilehub-1296620368',
}

export default awsmobile;
